### ISSUE TITLE
filter data by timestamp

### ISSUE THREAD

**Issue by st3b1t** [st3b1t/coinmap#1]
@smartm0use maybe you should enable issues in your repo, meanwhile I write here:

1) it could be a good idea to make sure that the Merchant creation time appears in the frontend, in this way the user can guess if it is an old and unreliable data or one recently entered

2) I was starting to do this by enabling metadata, some other parameters I added to optimize debugging... limit etc: https://github.com/st3b1t/coinmap/commit/fd2f8cd85c9c7514cad3e9c6a2986b7c496cb65c

**Comment by smartm0use** [comment]
Meanwhile I added issue section on my repository, thank you for your hint.

About your questions:
1. Yes, it is a good idea (some days ago I adopted the same solution on an another map project, glad to see we had the same idea in the same week), anyway we have to figure out how heavy became the query for OSM and how large became the output for requesting metadata for points coming from the whole globe. Let's try...
2. Why did you need `limit`? How to use it?

**Comment by st3b1t** [comment]
> 2\. Why did you need `limit`? How to use it?

useful in debug time on localhost


> 1. anyway we have to figure out how heavy became the query for OSM and how large became the output for requesting metadata for points coming from the whole globe. Let's try...

example of splitting query by country or other admin levels..
```
[out:json];
rel
  ["name:it"="Lazio"];
out geom;
map_to_area;
node
  ["currency:XBT"=yes]
  (area);
out;
```
try here: https://overpass-turbo.eu/s/1xZr

one way could be to create a data file for each country of the world .. and load them only when the map is in that area ecc ecc ecc..
this way you also optimize your import tasks which can be run in parallel!
how to do it? I don't have a practical idea at the moment :)

**Comment by smartm0use** [comment]
I accepted your pull request: let's see if we actually need to do optimizations on the queries.
